import HomeNav from "@/components/navbar"
import HomeFooter from "@/components/footer"
import { NextSeo } from "next-seo"

export default function Privacy() {
    return (
        <>
            <NextSeo
                title='Resume Analyzer - Privacy Policy'
                description='How Resume Analyzer collects, uses, and protects your information.'
                canonical={process.env.NEXT_PUBLIC_SITE_URL + '/privacy'}
                openGraph={{
                    url: process.env.NEXT_PUBLIC_SITE_URL + '/privacy',
                    title: 'Resume Analyzer - Privacy Policy',
                    description: 'How Resume Analyzer collects, uses, and protects your information.',
                    images: [
                        {
                            url: process.env.NEXT_PUBLIC_SITE_URL + '/full-logo.png',
                            width: 1024,
                            height: 1024,
                            alt: "Resume Analyzer Logo",
                            type: "image/png"
                        }
                    ],
                    siteName: "Resume Analyzer"
                }}
            />

            <HomeNav />
            <main className="mx-auto max-w-4xl px-6 pb-16 pt-28">
                <header className="space-y-4 pb-8">
                    <p className="text-2xl font-semibold uppercase text-slate-900">Privacy Policy - Resume Analyzer</p>
                    <div className="space-y-1 text-sm text-slate-600">
                        <p><span className="font-semibold text-slate-800">Site/Service:</span> Resume Analyzer (the "Service")</p>
                        <p><span className="font-semibold text-slate-800">Operated by:</span> Resume Analyzer (a service operated under RezPoint Inc.)</p>
                        <p><span className="font-semibold text-slate-800">Effective date:</span> February 1, 2026</p>
                        <p><span className="font-semibold text-slate-800">Last updated:</span> February 1, 2026</p>
                    </div>
                </header>

                <section className="space-y-4 text-base leading-relaxed text-slate-700">
                    <p>This Privacy Policy explains how Resume Analyzer ("Resume Analyzer," "we," "us," "our") collects, uses, discloses, stores, and protects information when you access or use our Service.</p>
                    <p>By using the Service, you consent to the practices described in this Privacy Policy. If you do not agree, do not use the Service.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">1) What we collect</h2>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">A) Account information</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Your sign-in is completed using your Google account and is handled by Google.</li>
                            <li>We receive limited account details (such as your email address and basic profile information) as permitted by your Google settings and consent screen.</li>
                        </ul>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">B) Content you upload or submit</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Resumes and files you upload.</li>
                            <li>Resume text extracted from those files.</li>
                            <li>Job descriptions, criteria, and inputs you provide for analysis.</li>
                            <li>Any notes or metadata you add in the Service.</li>
                        </ul>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">C) Analysis outputs</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Scores, summaries, recommendations, and other results generated by the Service.</li>
                        </ul>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">D) Token and purchase data</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Token purchase history, token balances, token usage events, timestamps, and related purchase metadata.</li>
                        </ul>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">E) Usage and device data</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Log data (IP address, device/browser info, pages/actions, timestamps, error logs, and security events).</li>
                            <li>Analytics necessary to operate and improve the Service.</li>
                        </ul>
                    </div>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">2) Authentication, storage, and infrastructure</h2>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">Google sign-in</h3>
                        <p>Sign-in is completed via Google and governed by Google&apos;s authentication flows. We do not receive your Google password.</p>
                    </div>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">Storage and database</h3>
                        <p>The Service uses Google Firebase and associated cloud services (including Firestore) to authenticate users, store resumes, store analysis inputs/outputs, and maintain operational logs.</p>
                        <p>Your information may be stored and processed on infrastructure located in Canada, the United States, or other jurisdictions where our service providers operate.</p>
                    </div>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">3) AI processing (parsing + analysis)</h2>
                    <p className="text-slate-700">To provide resume parsing and analysis, we transmit relevant content (e.g., resume text and your inputs) to Groq via its API:</p>
                    <ul className="list-disc space-y-2 pl-5 text-slate-700">
                        <li>Parsing uses the llama-3.1-8b-instant model.</li>
                        <li>Analysis uses the groq/compound model.</li>
                    </ul>
                    <p className="text-slate-700">Important: Do not upload sensitive information you do not want processed (e.g., government ID numbers, full financial account numbers). While we take reasonable steps to protect data, no system is perfectly secure.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">4) Payments and tokens (Stripe)</h2>
                    <p className="text-slate-700">Payments for tokens are processed through Stripe. We do not store full payment card details. Stripe processes payment information under its own policies.</p>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">No refunds for spent tokens</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>If you purchase tokens and spend any of them, those spent tokens are not refundable.</li>
                            <li>All token purchases are final except where refunds are required by applicable law (including Ontario/Canadian consumer protection laws).</li>
                            <li>If you believe a purchase is unauthorized or incorrect, contact us at support email as soon as possible.</li>
                        </ul>
                    </div>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">5) How we use your information</h2>
                    <ul className="list-disc space-y-2 pl-5 text-slate-700">
                        <li>Provide and operate the Service (uploading, storing, parsing, analyzing, and displaying results).</li>
                        <li>Maintain your account, token balance, and token usage tracking.</li>
                        <li>Prevent fraud, abuse, and repeated refund disputes after tokens are used.</li>
                        <li>Improve functionality, reliability, and user experience.</li>
                        <li>Secure the Service (monitoring, logging, auditing, and troubleshooting).</li>
                        <li>Comply with legal obligations and enforce our terms.</li>
                    </ul>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">6) Deletion and retention (including "deleted" results)</h2>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">User deletion in the UI</h3>
                        <p>If you delete your results or content through the Service, we will remove it from your active view and may remove it from active systems.</p>
                    </div>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">Retention for business and legal reasons (up to 5 years)</h3>
                        <p>Even if you delete results, Resume Analyzer may retain certain data for up to five (5) years for business and legal reasons, including:</p>
                        <ul className="list-disc space-y-2 pl-5">
                            <li>Maintaining auditable records of token usage and purchases.</li>
                            <li>Preventing misuse of refunds/chargebacks after tokens have been spent.</li>
                            <li>Complying with legal, tax, accounting, and regulatory obligations.</li>
                            <li>Resolving disputes and enforcing agreements.</li>
                            <li>Security investigations and fraud prevention.</li>
                        </ul>
                        <p>After the retention period, we will delete or anonymize retained data unless a longer period is required or permitted by law.</p>
                    </div>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">7) How we share information</h2>
                    <p className="text-slate-700">We may share information with:</p>

                    <div className="space-y-3">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">A) Service providers (processors)</h3>
                        <ul className="list-disc space-y-2 pl-5 text-slate-700">
                            <li>Hosting, storage, authentication, and database providers (Firebase/Google cloud services).</li>
                            <li>Payment processor (Stripe).</li>
                            <li>AI inference provider (Groq).</li>
                        </ul>
                        <p className="text-slate-700">These providers process data to deliver the Service and under their own applicable terms and safeguards.</p>
                    </div>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">B) Legal and compliance</h3>
                        <p>We may disclose information if required by law or if we reasonably believe it&apos;s necessary to:</p>
                        <ul className="list-disc space-y-2 pl-5">
                            <li>Comply with lawful requests (court orders, subpoenas).</li>
                            <li>Protect our rights, users, or the public.</li>
                            <li>Investigate fraud, security issues, or misuse.</li>
                        </ul>
                    </div>

                    <div className="space-y-3 text-slate-700">
                        <h3 className="text-lg font-headings font-semibold text-slate-900">C) Business transfers</h3>
                        <p>If RezPoint Inc. or the Service is involved in a merger, acquisition, reorganization, financing, bankruptcy, or sale of assets, information may be transferred as part of that transaction.</p>
                    </div>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">8) Data use rights (Resume Analyzer + parent company)</h2>
                    <p className="text-slate-700">By using the Service and submitting information, you grant Resume Analyzer and RezPoint Inc. the right, to the maximum extent permitted by law, to:</p>
                    <ul className="list-disc space-y-2 pl-5 text-slate-700">
                        <li>Use, store, reproduce, process, and modify the data you submit.</li>
                        <li>Create derivative works and improve the Service.</li>
                        <li>Use the data for internal analytics, operations, product development, and research.</li>
                        <li>Use aggregated and/or de-identified data for business purposes.</li>
                    </ul>
                    <p className="text-slate-700">Where feasible, we may aggregate or de-identify data. We do not guarantee that all uses will be de-identified.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">9) Security</h2>
                    <p className="text-slate-700">We use reasonable administrative, technical, and organizational measures intended to protect information. However, no method of transmission or storage is 100% secure.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">10) No liability for loss, breach, or stolen data</h2>
                    <p className="text-slate-700">To the maximum extent permitted by law:</p>
                    <ul className="list-disc space-y-2 pl-5 text-slate-700">
                        <li>Resume Analyzer and RezPoint Inc. are not liable for any loss, theft, unauthorized access, disclosure, alteration, unavailability, or destruction of data, including due to breaches, third-party actions, system failures, or events outside our control.</li>
                    </ul>
                    <p className="text-slate-700">Some jurisdictions do not allow certain limitations of liability; in those cases, these limitations apply only to the extent permitted by law.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">11) Your rights (Ontario/Canada)</h2>
                    <p className="text-slate-700">Depending on applicable law, you may have rights to:</p>
                    <ul className="list-disc space-y-2 pl-5 text-slate-700">
                        <li>Request access to the personal information we hold about you.</li>
                        <li>Request corrections to inaccurate information.</li>
                        <li>Request deletion (subject to the retention rules above).</li>
                        <li>Withdraw consent where processing is based on consent (where legally applicable), noting that withdrawal may limit your ability to use the Service.</li>
                    </ul>
                    <p className="text-slate-700">To make a request, contact us at our support email. We may need to verify your identity.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">12) Children</h2>
                    <p className="text-slate-700">The Service is not intended for children under 13, and we do not knowingly collect personal information from children under 13.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-6">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">13) Changes to this Privacy Policy</h2>
                    <p className="text-slate-700">We may update this policy from time to time. We will update the "Last updated" date and post the revised version. Continued use after updates means you accept the updated policy.</p>
                </section>

                <hr className="my-10 border-slate-200" />

                <section className="space-y-4 pb-8">
                    <h2 className="text-2xl font-headings font-semibold text-slate-900">14) Contact</h2>
                    <div className="space-y-1 text-slate-700">
                        <p><span className="font-semibold text-slate-900">Support email:</span> atinderpaulk@rezpoint.xyz</p>
                        <p><span className="font-semibold text-slate-900">Operator:</span> RezPoint Inc.</p>
                    </div>
                </section>
            </main>
            <HomeFooter />
        </>
    )
}
