import HomeNav from "@/components/navbar"
import HomeFooter from "@/components/footer"
import { NextSeo } from "next-seo"

export default function Privacy() {
    return (
        <>
            <NextSeo
                title='Resume Analyzer - Privacy Policy'
                description='How Resume Analyzer collects, uses, and protects your information.'
                canonical={process.env.NEXT_PUBLIC_SITE_URL + '/privacy'}
                openGraph={{
                    url: process.env.NEXT_PUBLIC_SITE_URL + '/privacy',
                    title: 'Resume Analyzer - Privacy Policy',
                    description: 'How Resume Analyzer collects, uses, and protects your information.',
                    images: [
                        {
                            url: process.env.NEXT_PUBLIC_SITE_URL + '/full-logo.png',
                            width: 1024,
                            height: 1024,
                            alt: "Resume Analyzer Logo",
                            type: "image/png"
                        }
                    ],
                    siteName: "Resume Analyzer"
                }}
            />

            <HomeNav />
            <main className="mx-auto w-full max-w-5xl px-6 pb-16 pt-28">
                <div className="rounded-2xl border border-slate-200/80 dark:border-slate-700/60 bg-white/80 dark:bg-midnight/80 backdrop-blur-md shadow-sm px-6 sm:px-10 py-8">
                    <h1 className="text-4xl sm:text-5xl font-headings font-semibold tracking-tight text-center text-slate-900 dark:text-white">
                        Resume Analyzer Privacy Policy
                    </h1>
                    <p className="mt-3 text-sm opacity-80 text-center font-main text-slate-700 dark:text-slate-300">
                        Last Updated: Feb 20, 2026
                    </p>

                    <div className="mt-8 space-y-7 text-base leading-relaxed font-main text-slate-800 dark:text-slate-100">
                        <p>
                            Resume Analyzer (&quot;we&quot;, &quot;our&quot;, &quot;the Service&quot;) helps you compare resumes to job descriptions using AI so you can see fit, gaps, and next steps.
                        </p>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">What Resume Analyzer Does</h2>
                            <p>
                                We let you upload a resume, paste a job description, and get AI-powered parsing, scoring, and tailored recommendations. Tokens you purchase fuel these AI runs.
                            </p>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Information We Collect</h2>
                            <ul className="list-disc pl-6 space-y-1">
                                <li><span className="font-semibold">Account (Google sign-in):</span> Email and basic profile details provided by Google. We never see your Google password.</li>
                                <li><span className="font-semibold">Uploads and inputs:</span> Resumes you upload, text extracted from them, job descriptions, criteria you enter, and any notes.</li>
                                <li><span className="font-semibold">Analysis outputs:</span> Scores, highlights, and recommendations generated by the Service.</li>
                                <li><span className="font-semibold">Tokens and purchases:</span> Token balances, usage timestamps, purchase history, and Stripe payment metadata (not full card numbers).</li>
                                <li><span className="font-semibold">Usage and device data:</span> IP address, browser/device info, pages/actions, timestamps, error and security logs used to keep the Service reliable.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">How We Use Information</h2>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Provide the core features: upload, parse, analyze, and display results tailored to your inputs.</li>
                                <li>Operate accounts, tokens, billing, and prevent fraud or chargeback abuse.</li>
                                <li>Improve quality, performance, and usability; troubleshoot errors.</li>
                                <li>Protect the Service, enforce policies, and comply with legal requirements.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">AI Processing (Groq)</h2>
                            <p>We send relevant text (resume content and your inputs) to Groq&apos;s API to produce parsing and analysis.</p>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Parsing uses the <code className="font-mono text-sm">llama-3.1-8b-instant</code> model.</li>
                                <li>Analysis uses the <code className="font-mono text-sm">groq/compound</code> model.</li>
                            </ul>
                            <p>Do not upload sensitive data you do not want processed (e.g., government IDs or full financial account numbers).</p>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Storage &amp; Security</h2>
                            <p>Authentication, storage, and logs run on Google Firebase (including Firestore). Data may be processed in Canada, the United States, or other regions where Google Cloud operates.</p>
                            <p>Your uploads, analysis inputs/outputs, and operational logs are stored in our cloud environment. We apply reasonable safeguards, but no system is 100% secure.</p>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Payments &amp; Tokens (Stripe)</h2>
                            <p>Stripe processes payments. We do not store full payment card details; Stripe handles them under its own terms.</p>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Token purchases are generally final; spent tokens are not refundable except where required by law.</li>
                                <li>If you suspect an unauthorized charge, contact us and your payment provider promptly.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Data Sharing</h2>
                            <p>We share data only to operate the Service or when law requires:</p>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Service providers: Firebase/Google Cloud (auth, storage), Groq (AI processing), Stripe (payments).</li>
                                <li>Legal/compliance: to satisfy lawful requests, protect rights, investigate abuse, or meet regulatory obligations.</li>
                                <li>Business transfers: if RezPoint Inc. or the Service is involved in a merger, acquisition, financing, or sale of assets.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Retention &amp; Deletion</h2>
                            <p>Deleting items in the UI removes them from your active view. Certain records may remain for required reasons.</p>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Operational, billing, and security logs (including token usage and purchase history) may be retained for up to five (5) years for auditing, fraud prevention, legal, tax, and accounting obligations.</li>
                                <li>After the retention period, we delete or anonymize data unless a longer period is required by law.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Children’s Privacy</h2>
                            <p>The Service is not directed to children under 13, and we do not knowingly collect personal information from them.</p>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Your Choices &amp; Rights</h2>
                            <ul className="list-disc pl-6 space-y-1">
                                <li>Access or update your Google account details through Google.</li>
                                <li>Request access, correction, or deletion of personal information (subject to the retention rules above) by emailing us.</li>
                                <li>You may stop using the Service at any time; some records may remain as described in Retention.</li>
                            </ul>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Changes to This Policy</h2>
                            <p>We may update this page from time to time. The most current version (and date) will always appear here.</p>
                        </section>

                        <section className="space-y-2">
                            <h2 className="text-2xl font-headings font-semibold text-slate-900 dark:text-white">Contact</h2>
                            <p>
                                Email:{' '}
                                <a className="underline underline-offset-4 text-eazy-main-100 hover:text-top-orange" href="mailto:atinderpaulk@rezpoint.xyz">
                                    atinderpaulk@rezpoint.xyz
                                </a>
                            </p>
                            <p>Operator: RezPoint Inc.</p>
                        </section>
                    </div>
                </div>
            </main>
            <HomeFooter />
        </>
    )
}
